import { VerticalBox } from "std-widgets.slint";
import { Theme } from "../styles/themes.slint";
import { DynamicButton } from "buttons.slint";
import { Icons } from "../styles/icons.slint";


export component TopBar {
    callback upload-clicked();
    callback convert-clicked();
    callback clear-clicked();
    Rectangle {
        background: Theme.background;
        height: 80px;

        HorizontalLayout {
            padding: 10px;
            spacing: 10px;
            VerticalLayout {
                Text {
                    text: "PDF Editor";
                    color: Theme.main-font-color;
                    font-size: Theme.main-text-size;
                    font-weight: Theme.font-weight-bold;
                }

                Text {
                    text: "Merge, reorder and edit your PDF documents";
                    color: Theme.secondary-font-color;
                    font-size: Theme.secondary-text-size;
                }
            }

            DynamicButton {

                title: "Add Files";
                icon: Icons.plus-icon;
                background-color: #2196F3; 
                height: parent.height / 2 + 10px;
                hover-color: #1976D2;
                pressed-color: #0D47A1;
                clicked => {
                    root.upload-clicked();
                }
            }

            DynamicButton {
                title: "Convert";
                icon: Icons.loop-circular-arrows;
                background-color: #4CAF50;  // Green
                hover-color: #45a049;
                height: parent.height / 2 + 10px;
                pressed-color: #3d8b40;
                clicked => {
                    root.convert-clicked();
                }
            }

            DynamicButton {
                title: "Clear";
                icon: Icons.clear-icon;
                background-color: #f44336;  // Red
                hover-color: #d32f2f;
                height: parent.height / 2 + 10px;
                pressed-color: #b71c1c;
                clicked => {
                    root.clear-clicked();
                }
            }
        }
    }
}
