export global Theme {
    out property <brush> background: #ffffff;

    out property <brush> main-font-color: #000000;
    out property <int> font-weight-bold: 700;
    out property <int> font-weight-semibold: 500;
    out property <brush> secondary-font-color: #5d5a5a;
    out property <length> main-text-size: 18px;
    out property <length> secondary-text-size: 12px;

    out property <length> button-icon-size: 20px;
    out property <brush> file-window-background: #cfcfcf;
}
